from pathlib import Path
import os
import subprocess
import re

this_dir = Path(__file__).parent

def get_command_from_build_ninja(rule):
    papermario = this_dir / "papermario"
    build_ninja = papermario / "build.ninja"

    with build_ninja.open("r") as f:
        lines = f.readlines()

    command = None
    for i, line in enumerate(lines):
        if line.startswith(f"rule {rule}"):
            command = lines[i + 1]
            command = command[command.find("=")+1:].strip()
            break

    if not command:
        raise Exception(f"Could not find rule '{rule}' in build.ninja")

    if rule == "ld":
        command = command.replace(" ", " -T ../src/symbol_addrs.txt ", 1)

    command = "cd papermario && " + command.replace("$version", "us")

    def run(options):
        my_command = command
        for key, value in options.items():
            my_command = my_command.replace(f"${key}", value)
        if os.system(my_command) != 0:
            exit(1)

    return run

def objdump_to_dict(infname):
    output = subprocess.check_output(["mips-linux-gnu-objdump", infname, "-d", "-f"]).decode("utf-8")
    lines = output.splitlines()
    start_of_func_re = re.compile(r"([0-9a-f]+) <(.+)>:")
    funcs_dict = {}

    for i, line in enumerate(lines):
        if match := start_of_func_re.match(line):
            name = match.group(2)

            asm_list = []
            for i, line in enumerate(lines[i+1:]):
                parts = line.split("\t", 2)
                if len(parts) < 2 or parts[1] == "...":
                    break
                as_int = int(parts[1].strip(), 16)
                as_text = parts[2].replace("\t", " ")

                asm_list.append([ as_int, as_text ])

            funcs_dict[name] = asm_list

    return funcs_dict

cc = get_command_from_build_ninja("cc")
ld = get_command_from_build_ninja("ld")

cc({ "in": "../src/patches.c", "out": "../build/patches.o" })
ld({ "in": "../src/patches.ld", "out": "../build/patches.elf", "mapfile": "../build/patches.map" })

funcs_dict = objdump_to_dict("build/patches.elf")

with (this_dir / "build" / "patches.mjs").open("w") as f:
    f.write("// Generated by build.py\n")

    for name, asm in objdump_to_dict("build/patches.elf").items():
        f.write("\n")
        f.write(f"export const {name} = [\n")
        for as_int, as_text in asm:
            f.write(f"    0x{as_int:08x}, // {as_text}\n")
        f.write("]\n")

with (this_dir / "build" / "patches.js").open("w") as f:
    f.write("// Generated by build.py\n")
    f.write("\n")
    f.write("module.exports = {}\n")

    for name, asm in objdump_to_dict("build/patches.elf").items():
        f.write("\n")
        f.write(f"module.exports.{name} = [\n")
        for as_int, as_text in asm:
            f.write(f"    0x{as_int:08x}, // {as_text}\n")
        f.write("]\n")

with (this_dir / "build" / "patches.d.ts").open("w") as f:
    f.write("// Generated by build.py\n")

    for name, asm in funcs_dict.items():
        f.write("\n")
        f.write(f"export const {name}: number[]\n")
